In [1]:
# TensorFlow and tf.keras
import tensorflow as tf

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt
import time

print(tf.__version__)

2.3.1


## 基礎操作

In [9]:
# 定義一個隨機數純量（0 維陣列）
random_float = tf.random.uniform(shape=())
print("0 維陣列 ",random_float)

# 定義一個有2個元素的零向量（1 維陣列）
zero_vector = tf.zeros(shape=(2))
print("1 維陣列 ",zero_vector)

# 定義兩個2×2的常量矩陣（2 維陣列）
A = tf.constant([[1., 2.], [3., 4.]])
B = tf.constant([[5., 6.], [7., 8.]])
print("2 維陣列 ",A)
print("2 維陣列 ",B)

0 維陣列  tf.Tensor(0.32347238, shape=(), dtype=float32)
1 維陣列  tf.Tensor([0. 0.], shape=(2,), dtype=float32)
2 維陣列  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
2 維陣列  tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [8]:
# 查看矩陣A的形狀、類型和值
print(A.shape)      
print(A.dtype)      
print(A.numpy())

(2, 2)
<dtype: 'float32'>
[[1. 2.]
 [3. 4.]]


In [6]:
C = tf.add(A, B)    # 計算矩陣A和B的和
D = tf.matmul(A, B) # 計算矩陣A和B的乘積

## 自動推導機制 

In [11]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:     # 在 tf.GradientTape() 的上下文內，所有計算步驟都會被記錄以用於推導
    y = tf.square(x)
y_grad = tape.gradient(y, x)        # 計算y關於x的導數

print(y, y_grad)

tf.Tensor(9.0, shape=(), dtype=float32) tf.Tensor(6.0, shape=(), dtype=float32)


In [15]:
X = tf.constant([[1., 2.], [3., 4.]])
y = tf.constant([[1.], [2.]])
w = tf.Variable(initial_value=[[1.], [2.]])
b = tf.Variable(initial_value=1.)

with tf.GradientTape() as tape:
    L = tf.reduce_sum(tf.square(tf.matmul(X, w) + b - y))

w_grad, b_grad = tape.gradient(L, [w, b])        # 計算L(w, b)關於w, b的偏導數

print(L)
print(w_grad)
print(b_grad)

tf.Tensor(125.0, shape=(), dtype=float32)
tf.Tensor(
[[ 70.]
 [100.]], shape=(2, 1), dtype=float32)
tf.Tensor(30.0, shape=(), dtype=float32)


## 線性回歸

In [16]:
import numpy as np

X_raw = np.array([2013, 2014, 2015, 2016, 2017], dtype=np.float32)
y_raw = np.array([12000, 14000, 15000, 16500, 17500], dtype=np.float32)

X = (X_raw - X_raw.min()) / (X_raw.max() - X_raw.min())
y = (y_raw - y_raw.min()) / (y_raw.max() - y_raw.min())

In [22]:
X = tf.constant(X)
y = tf.constant(y)

a = tf.Variable(initial_value=0.)
b = tf.Variable(initial_value=0.)
variables = [a, b]

num_epoch = 1
optimizer = tf.keras.optimizers.SGD(learning_rate=5e-4)
for e in range(num_epoch):
    # 使用tf.GradientTape()記錄損失函數的梯度資訊
    with tf.GradientTape() as tape:
        y_pred = a * X + b
        loss = tf.reduce_sum(tf.square(y_pred - y))
    # TensorFlow自動計算損失函數關於自變數（模型參數）的梯度
    grads = tape.gradient(loss, variables)
    print (grads)

    # TensorFlow自動根據梯度更新參數
    optimizer.apply_gradients(grads_and_vars=zip(grads, variables))

# print(a, b)

[<tf.Tensor: shape=(), dtype=float32, numpy=-3.9545455>, <tf.Tensor: shape=(), dtype=float32, numpy=-5.4545455>]
tf.Tensor(-3.9545455, shape=(), dtype=float32)
tf.Tensor(-5.4545455, shape=(), dtype=float32)
